config/routes.rb
Blog::Application.routes.draw do
  
  root  :to => 'posts#index'
  resources :posts
   match '/test_queries', to: 'posts#test_queries', via: :get
   
  namespace :admin do
    resources :posts
    match '/test_queries', to: 'posts#test_queries'
    match '/say_hello', to: 'posts#say_hello'
   end
   

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title,:name,:state,:latitude,:longitude,:gmaps,:population
    
  acts_as_gmappable# :process_geocoding => true
  
  def gmaps4rails_address
    "#{self.name}, #{self.state}"
  end
  
  
  #validates :title , presence: true 
  # validates_presence_of :title, :message=>"Please Enter Title"
end

app/controllers/admin/posts_controller.rb
#class PostsController < ApplicationController
class Admin::PostsController < ApplicationController
	def index
		#@posts = Post.find(:all) #all posts
		@posts = Post.all
		@first_post = Post.find(:first)
		@second_post = Post.find(2)
		#@second_post = Post.find_by_id(2)
		#@title_post = Post.find_by_title("First Post")
		#@second_post = Post.find(2)
		@third_post = Post.find(:all,:conditions=>["id=?",3] )
		@second_post.title = "Our Second Post"
		@second_post.save
		#@second_post.update_attribute(:content,"Our Second Post Content")
		#@second_post.update_attributes(:title=>"2nd post",:content=>"this is Second Post Content")
		
		
		#the below query is to select the columns id,title,price,subject_id from Books table,it will only select the columns that is 
       #specified in the query with :select=>  option...........
     @selected_column  = Post.find(:all, :select => 'id,title,created_at,updated_at', :conditions => ["id >= ?",5])
	end	
	
	def show
		@post = Post.find(params[:id])
	end
	
	def new
		@post = Post.new
	end
	
	def create
		@post = Post.new(params[:post])
		
		if @post.save 
			redirect_to posts_path , :notice => "Post was saved successfully"
		else
			render "new"
		end		
	end
	
	def edit
		@post = Post.find(params[:id])
	end
	
	def update
		@post = Post.find(params[:id])
		
		if @post.update_attributes(params[:post])
			# redirect_to :action => 'index', :notice => "Post was updated successfully this is to check"
			redirect_to posts_path , :notice => "Post was updated successfully"
		else	
			render "edit"
		end	
	end
	
	def destroy	
		#Post.find(params[:id]).destroy
		@post = Post.find(params[:id])
		@post.destroy	
		redirect_to posts_path ,:notice => "Your #{@post.title} post has been deleted "
	end
	
	def test_queries
		@posts = Post.all
	end
	
	def say_hello
		@third_post = Post.find(:all,:conditions=>["id=?",3] )
		@rd = session[:third] = @third_post
		
		@rd.each do |t|	
			po = t.title
			@like_query = Post.find(:all,:conditions => "title like '%"+po+"%'")
		end
		
		 #prop_name = params[:q]
		#@property = Property.find(:all , :conditions=>"name like '%"+prop_name+"%'")
		
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		
=begin
These are the files added when gmaps4rails gem is installed
D:\rails_demo_app\ROR_TEST\Blog_test\blog>rails g gmaps4rails:install
        SECURITY WARNING: No secret option provided to Rack::Session::Cookie.
        This poses a security threat. It is strongly recommended that you
        provide a secret to prevent exploits that may be possible from crafted
        cookies. This will not be supported in future versions of Rack, and
        future versions will even invalidate your existing user cookies.

        Called from: C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/action
pack-3.2.8/lib/action_dispatch/middleware/session/abstract_store.rb:28:in `initi
alize'.

      create  app/assets/javascripts/gmaps4rails/gmaps4rails.base.js.coffee
      create  app/assets/javascripts/gmaps4rails/gmaps4rails.googlemaps.js.coffe
e
      create  app/assets/javascripts/gmaps4rails/gmaps4rails.openlayers.js.coffe
e
      create  app/assets/javascripts/gmaps4rails/gmaps4rails.bing.js.coffee
      create  app/assets/javascripts/gmaps4rails/gmaps4rails.mapquest.js.coffee
      create  app/assets/stylesheets/gmaps4rails.css
**************************************
Google Maps For Rails

=end
		
		
		
		
		@posts = Post.find(:all) #all posts
		#@posts = Post.all
		#@json = @posts.to_gmaps4rails
		@json = Post.all.to_gmaps4rails
		@first_post = Post.find(:first)
		@second_post = Post.find(18)
		#@second_post = Post.find_by_id(2)
		#@title_post = Post.find_by_title("First Post")
		#@second_post = Post.find(2)
		@third_post = Post.find(:all,:conditions=>["id=?",3] )
		#@second_post.title = "Our Second Post"
		#@second_post.save
		#@second_post.update_attribute(:content,"Our Second Post Content")
		#@second_post.update_attributes(:title=>"2nd post",:content=>"this is Second Post Content")
		
		
		#the below query is to select the columns id,title,price,subject_id from Books table,it will only select the columns that is 
       #specified in the query with :select=>  option...........
     @selected_column  = Post.find(:all, :select => 'id,title,created_at,updated_at', :conditions => ["id >= ?",5])
	end	
	
	def show
		@post = Post.find(params[:id])
	end
	
	def new
		@post = Post.new
	end
	
	def create
		@post = Post.new(params[:post])
		
		if @post.save 
			redirect_to posts_path , :notice => "Post was saved successfully"
		else
			render "new"
		end		
	end
	
	def edit
		@post = Post.find(params[:id])
	end
	
	def update
		@post = Post.find(params[:id])
		
		if @post.update_attributes(params[:post])
			# redirect_to :action => 'index', :notice => "Post was updated successfully this is to check"
			redirect_to posts_path , :notice => "Post was updated successfully"
		else	
			render "edit"
		end	
	end
	
	def destroy	
		#Post.find(params[:id]).destroy
		@post = Post.find(params[:id])
		@post.destroy	
		redirect_to posts_path ,:notice => "Your #{@post.title} post has been deleted "
	end
	
	def test_queries
		@posts = Post.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/index.html.erb
   
 <%= stylesheet_link_tag  "test" %>
hello index
<%=  ::Rails.root%>
<br/>
Displaying only first post Title: <%=  @first_post.title%><br/>

Displaying only second post Title: <%=  @second_post.title%><br/>

 Third Post :<% @third_post.each do |post|%>
							<%= post.title%>
					      <% end %>  			
<br/>
<br/>
<br/>

Displaying All Posts: 
		<table style="border:1px solid #A292FF; background: none repeat scroll 0 0 #1B1B24;color: #A292FF;">
		<% @posts.each do |post|%>
			<tr  style="border:10px solid #ffffff;">
				<td>Post Id:  <%= link_to post.id, post %></td>
				<td>Title: </td> <td><%= link_to post.title, post %> </td> 
				<td>Content: </td> <td><%= post.content%></td>
				<td><%= link_to 'Edit Post', edit_post_path(post) %> |</td>
				<td><%= link_to 'Delete Post', post , :confirm=>"Are you Sure you want to delete #{post.title}?" ,:method=> :delete %></td>
			</tr>
					
			<tr>
				
			</tr>
		<% end %>	
	      </table>
	       
<p><%= link_to 'Add a New Post' , new_post_path ,:class=>"button-how"%></p>
<p><%#= link_to 'Test Queries Method' ,  :action => "test_queries" %></p>
<p><%= link_to 'Test Queries Method' ,  admin_test_queries_path %></p>
<p><%#= link_to 'Display Queries' ,  :action => "say_hello" %></p>
<p><%= link_to 'Say Hello Method' , admin_say_hello_path %></p>

Selected Column :

<% @selected_column.each do |s|%>
	ID: <%= s.id%> <br/>
	Title: <%= s.title%><br/>
	Created At: <%= s.created_at%><br/>
	Updated At: <%= s.updated_at%><br/>
	
<% end %>

app/views/admin/posts/say_hello.html.erb
<h1>Hiii
	<% @third_post.each do |post|%>
		<%= post.title%>
	<% end %>  
</h1>	
	<hr/>
	<% @rd.each do |three| %>
		ID: <%= three.id %>
		Title:<%= three.title %>
	<% end %>


<hr/>

<%= @like_query %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag 'gmaps4rails' %>
  <%= csrf_meta_tags %>
</head>
<body>



<div id="container">

  <div id="header">
      <%= link_to 'Blog by Anchal' , root_path %>
  </div> <!-- end header -->
  
  
  <div id="nav">
    <ul>
        <li>
          <%= link_to 'Home' , root_path %>          
        </li>
        <li>
          <%= link_to 'Admin' , {:controller=>'admin/posts',:action=>'index'} %>
        </li>
        <li>
          <%= link_to 'Add a New Post' , new_post_path ,:class=>"button-how"%>
        </li>
        <li>
          <%= link_to 'Display Queries' ,  :action => "test_queries" %>
        </li>

    </ul>
  </div>  <!-- end nav div -->
  
  
  <div id="content">

      <% flash.each do |key,value| %>
        <p id="message"><%= value%></p>
      <% end %>

      <%= yield  %>
  </div> <!-- end content div -->

  <div id="footer">
      &copy; Blog by Anchal <%= Date.today.year %><%= yield :scripts %>
  </div><!-- end footer -->
  
  
</div><!-- end container div -->
</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post do |f| %>
<table>
	<tr><td> <%= f.label :title %></td><td><%= f.text_field :title ,:id=>"new_title"%> </td></tr>
	<tr><td> <%= f.label :content %></td><td><%= f.text_area :content,:id=>"new_content"%> </td></tr>
	<tr><td></td><td><%= f.submit "Update Post" %> </td></tr>
</table>
<% end %>

  <td><%= link_to 'Back to Post List', posts_path %> 

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'gmaps4rails' %>
<% flash[:notice] -%>
<div id="notice"><%= flash[:notice] %></div>
   

hello index
<%=  ::Rails.root%>
<br/>
Displaying only first post Title: <%=  @first_post.title%><br/>

Displaying only second post Title: <%=  @second_post.title%><br/>

 Third Post :<% @third_post.each do |post|%>
							<%= post.title%>
					      <% end %>  			
<br/>
<br/>
<br/>

Displaying All Posts: 
		<!-- <table style="border:1px solid #A292FF; background: none repeat scroll 0 0 #1B1B24;color: #A292FF;"> -->
		<table >
		<% @posts.each do |post|%>
			<tr  style="border:10px solid #ffffff;">
				<td>Post Id:  <%= link_to post.id, post %></td>
				<td>Title: </td> <td><%= link_to post.title, post %> </td> 
				<td>Content: </td> <td><%= post.content%></td>
				<td><%= link_to 'Edit Post', edit_post_path(post) %> |</td>
				<td><%= link_to 'Delete Post', post , :confirm=>"Are you Sure you want to delete #{post.title}?" ,:method=> :delete %></td>
			</tr>
					
			<tr>
				
			</tr>
		<% end %>	
	      </table>
	       
Displaying All Posts with map: 
		<!-- <table style="border:1px solid #A292FF; background: none repeat scroll 0 0 #1B1B24;color: #A292FF;"> -->
		<table >
		
	      </table>	       
	       
	       
	       
	       
	       
	       
	       
	       
	       
	       
	       
<p><%= link_to 'Add a New Post' , new_post_path ,:class=>"button-how"%></p>
<p><%= link_to 'Display Queries' ,  :action => "test_queries" %></p>


Selected Column :

<% @selected_column.each do |s|%>
	ID: <%= s.id%> <br/>
	Title: <%= s.title%><br/>
	Created At: <%= s.created_at%><br/>
	Updated At: <%= s.updated_at%><br/>
	
<% end %>

<div class="map_container"> 
  <div id="map" class="gmaps4rails_map"><%= gmaps4rails(@json) %></div> 
</div>


app/views/posts/new.html.erb
<h1> Add a New Post</h1>

<%= form_for @post do |f| %>
<table>
	<tr><td> <%= f.label :title %></td><td><%= f.text_field :title ,:id=>"new_title"%> </td></tr>
	<tr><td> <%= f.label :content %></td><td><%= f.text_area :content,:id=>"new_content"%> </td></tr>
	<tr><td></td><td><%= f.submit "Add a New Post" %> </td></tr>
</table>
<% end %>

  <td><%= link_to 'Back to Post List', posts_path %> 

app/views/posts/show.html.erb
<% flash[:notice] -%>
<div id="notice"><%= flash[:notice] %></div>


<p><h1>Displaying Post:</h1>
		<table border="1">
		
			<tr>
				<td>Title: </td> <td><%= @post.title%> <hr/></td> 
			</tr>
				
			<tr>
				<td>Content: </td> <td><%= @post.content%><hr/></td>
				
			</tr>
			<tr>
				<td><small>Created At:</td> <td style="padding-left:2px;"><%=  @post.created_at%></small><hr/></td>
			</tr>
	      </table>
	       <td><%= link_to 'Back to Post List', posts_path %> 
</p>

app/views/posts/test_queries.html.erb
   This page is to test the queries....
 <%= stylesheet_link_tag  "test" %>

<%=  ::Rails.root%>
<br/>
<h1>Displaying only first post Title: <%#=  @first_post.title%><br/></h1>

Displaying only second post Title: <%#=  @second_post.title%><br/>

 Third Post :<%# @third_post.each do |post|%>
							<%#= post.title%>
					      <%# end %>  			
<br/>
<br/>
<br/>

Displaying All Posts: 
		<table style="border:1px solid #A292FF; background: none repeat scroll 0 0 #1B1B24;color: #A292FF;">
		<% @posts.each do |post|%>
			<tr  style="border:10px solid #ffffff;">
				<td>Post Id:  <%= link_to post.id, post %></td>
				<td>Title: </td> <td><%= link_to post.title, post %> </td> 
				<td>Content: </td> <td><%= post.content%></td>
				<td><%= link_to 'Edit Post', edit_post_path(post) %> |</td>
				<td><%= link_to 'Delete Post', post , :confirm=>"Are you Sure you want to delete #{post.title}?" ,:method=> :delete %></td>
			</tr>
					
			<tr>
				
			</tr>
		<% end %>	
	      </table>
	       
<p><%= link_to 'Add a New Post' , new_post_path ,:class=>"button-how"%></p>
<p><%= link_to 'Back to Post list' , posts_path ,:class=>"button-how"%></p>


Selected Column :

<%# @selected_column.each do |s|%>
	ID: <%#= s.id%> <br/>
	Title: <%#= s.title%><br/>
	Created At: <%#= s.created_at%><br/>
	Updated At: <%#= s.updated_at%><br/>
	
<%# end %>